version: '3.8'

services:
  zookeeper:
    extends:
      file: docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: docker-compose.yml
      service: kafka

  tpe-tracker:
    extends:
      file: docker-compose.yml
      service: tpe-tracker

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
